### ISSUE TITLE
just wanna ask

### ISSUE THREAD

**Issue by shubh402** [cleverhare/cleverhare#1]
Hey man just wanna ask you got into IIT?

**Comment by cleverhare** [comment]
No bro I didn't but I am an aspirant

**Comment by cleverhare** [comment]
Lets be friend.

**Comment by Imshubh69** [comment]
> Lets be friend.

sure can I have your email id and stuff?

**Comment by cleverhare** [comment]
For sure brother, My email ID is soumyajitbrah@gmail.com My FIverr Account: https://fiverr.com/cleverhare My Insta Account: https://www.instagram.com/cleverhare.official/ and My Linked in account https://www.linkedin.com/in/soumyajit-coder/

**Comment by cleverhare** [comment]
Okay

**Comment by cleverhare** [comment]
Hey

**Comment by cleverhare** [comment]
I dont think this issue is required anymore
